Step data v2
Walkover-Web-Solution/socket-flow-UI pull request #285
Opened 2023-11-08 12:51 UTC by Arpitjain111

2023-11-09 05:50 UTC, rudrakachhawa commented on src/store/stepsV2/stepReducerV3.ts
> +    const tempInstance = cloneDeep(state[action.payload.currentScriptId][action.payload.currentStepId]?.draft)
prefer action destructuring here to use script id and step id

2023-11-09 06:09 UTC, rudrakachhawa commented on src/store/stepsV2/stepReducerV3.ts
> +    })
isLoading bhi paritcular step k liye true false krna he

2023-11-09 06:46 UTC, rudrakachhawa commented on src/store/stepsV2/stepReducerV3.ts
> +}
api call abhi har bar step ke click par ho rahi he , uski wajah se draft wala code update ho jata he thats why mujhe saved code hi dikhta he , draft nahi dikhta he

2023-11-20 09:42 UTC, SiDDhartharG requested changes

2023-11-20 09:42 UTC, SiDDhartharG commented on src/components/masterSliderComponent/masterSliderComponent.tsx
> +        } else {
.

2023-11-20 09:42 UTC, SiDDhartharG commented on src/components/masterSliderComponent/masterSliderComponent.tsx
> +        } else {
nagetion on function

2023-11-20 09:42 UTC, SiDDhartharG commented on src/components/responseAndConsoleTabs/responseAndConsoleTabs.tsx
> +  const { dryRunResponseForStep } = useCustomSelector((state: $ReduxCoreType) => ({
.

2023-11-20 09:42 UTC, SiDDhartharG commented on src/components/responseAndConsoleTabs/responseAndConsoleTabs.tsx
> +  const { dryRunResponseForStep } = useCustomSelector((state: $ReduxCoreType) => ({
lastInvocationData

2023-11-20 09:42 UTC, SiDDhartharG commented on src/components/responseAndConsoleTabs/responseAndConsoleTabsV2.tsx
> +  const dryRunResponseForStep = useSelector((state) => state.stepsDataV3?.[currentScriptId]?.[currentStepId]?.dryRunResponseForStep)
useCustomSelector

2023-11-20 09:42 UTC, SiDDhartharG commented on src/components/saveButton/saveButton.tsx
> +  const currentSlugName = useCustomSelector((state) => state.appInfo.currentSlugName)
useCustomSelector

2023-11-20 09:42 UTC, SiDDhartharG commented on src/components/saveButton/saveButton.tsx
> +export function SaveButton({ type, code, response, isDisabled }) {
hoc

2023-11-20 09:42 UTC, SiDDhartharG commented on src/components/stepNameComponent/resetButtonForSlider.tsx
> +  const flowJsonBlocks = useSelector((state) => state?.flowJsonV2?.flowJson?.blocks?.[currentSlugName])
useCustomSelector

2023-11-20 09:42 UTC, SiDDhartharG commented on src/components/stepNameComponent/resetButtonForSlider.tsx
> +export default function ResetButtonForSlider() {
HOC

2023-11-20 09:42 UTC, SiDDhartharG commented on src/components/stepNameComponent/stepNameComponentV2.tsx
> +  const currentStepId = useSelector((state) => state.appInfo.currentStepId)
useCustomSelector

2023-11-20 09:42 UTC, SiDDhartharG commented on src/components/stepNameComponent/stepNameComponentV2.tsx
> +export function StepNameComponent({ showAskAiButton = true }) {
HOC

2023-11-20 09:42 UTC, SiDDhartharG commented on src/store/combineReducer.js
> +  stepsDataV3: stepsDataV3Reducer,
ADD in ReduxCore 
new data type

2023-11-20 09:42 UTC, SiDDhartharG commented on src/store/stepsV2/stepSliceV3.ts
> +  initialState,
data type if inti value

2023-11-20 12:33 UTC, closed without merging