trigger and cron 3 dots button for delete and closes the sliders if o…
Walkover-Web-Solution/socket-flow-UI pull request #294
Opened 2023-11-10 08:45 UTC by NJ-jain

…pen while deleting

2023-11-10 08:47 UTC, NJ-jain reviewed
reviewed myself

2023-11-13 06:11 UTC, piyusssshh approved these changes

2023-11-15 07:33 UTC, SiDDhartharG requested changes

2023-11-15 07:33 UTC, SiDDhartharG commented on src/components/functiondashboard/workFlow/workFlowComponent/cronComponent/cronComponent.js
> +  const open = Boolean(anchorEl)
do we need this extra variable here "open"?

2023-11-15 13:22 UTC, SiDDhartharG approved these changes

2023-11-15 13:22 UTC, merged