Feature/show all athorization
Walkover-Web-Solution/socket-flow-UI pull request #296
Opened 2023-11-10 09:21 UTC by Dpksolanki

2023-11-14 09:43 UTC, SiDDhartharG requested changes

2023-11-14 09:43 UTC, SiDDhartharG commented on src/App.js
> +    auth
@Dpksolanki

2023-11-14 09:43 UTC, SiDDhartharG commented on src/App.js
> +    template,
sdfsdffs

2023-11-15 07:32 UTC, SiDDhartharG requested changes

2023-11-15 07:32 UTC, SiDDhartharG commented on src/components/authDataTable/authDataTable.js
> +  const usersList = useCustomSelector((state) => listOfUsers(state))
update this as per the discursion
we already have user id mapping

2023-11-15 17:32 UTC, Dpksolanki commented on src/App.js
> +    auth
it resolve

2023-11-15 17:32 UTC, Dpksolanki commented on src/components/authDataTable/authDataTable.js
> +  const usersList = useCustomSelector((state) => listOfUsers(state))
Done

2023-11-16 04:53 UTC, SiDDhartharG approved these changes

2023-11-16 10:49 UTC, SiDDhartharG approved these changes

2023-11-16 10:50 UTC, merged