changes in ui to get the step error visible in ui when dry run runs the exectional script
Walkover-Web-Solution/socket-flow-UI pull request #303
Opened 2023-11-15 12:44 UTC by NJ-jain

reviewed myself

2023-11-15 13:04 UTC, NJ-jain commented
pleasee check this pr on your  system and check the ui for this also !!
and for runnig this branch need to have backend branch named "change-steporder-to-json" and add env -
WRITE_INDEX= local_json_alias_1
READ_INDEX = local_json_alias

2023-11-16 04:38 UTC, SiDDhartharG requested changes

2023-11-16 04:38 UTC, SiDDhartharG commented on src/components/functiondashboard/workFlow/workFlowComponent/apiFunctionComponent/apiFunctionComponent.js
> +  const blockError = useCustomSelector((state) => state.invocationV2.invocationData.stepOrder[id]?.success) ?? true
const blockError = useCustomSelector((state) => state.invocationV2.invocationData.stepOrder?[id]?.success) ?? true

2023-11-16 04:38 UTC, SiDDhartharG commented on src/components/functiondashboard/workFlow/workFlowComponent/ifComponent/ifComponent.js
> +  const blockError = useCustomSelector((state) => state.invocationV2?.invocationData?.stepOrder[stepId]?.success) ?? true
const blockError = useCustomSelector((state) => state.invocationV2.invocationData.stepOrder?[id]?.success) ?? true

2023-11-16 04:38 UTC, SiDDhartharG commented on src/components/functiondashboard/workFlow/workFlowComponent/pluginComponent/pluginComponent.js
> +  const blockError = useCustomSelector((state) => state.invocationV2.invocationData.stepOrder[id]?.success) ?? true
const blockError = useCustomSelector((state) => state.invocationV2.invocationData.stepOrder?[id]?.success) ?? true

2023-11-16 07:11 UTC, SiDDhartharG approved these changes

2023-11-18 05:05 UTC, closed without merging