Via 1108/user onboarding and user flow
Walkover-Web-Solution/socket-flow-UI pull request #400
Opened 2023-11-24 06:59 UTC by BhojrajPathak001

pr with conflicts

2023-11-24 07:13 UTC, SiDDhartharG requested changes

2023-11-24 07:13 UTC, SiDDhartharG commented on src/components/functiondashboard/workFlow/workFlowComponent/flowJsonHeader/triggerHeaderBox.tsx
> +  // const setPluginInfoOfAirTableFunction = (plugin) => {
.

2023-11-24 09:54 UTC, SuruGuptaa approved these changes

2023-11-25 07:01 UTC, SiDDhartharG approved these changes

2023-11-25 07:01 UTC, merged